name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/eclipse-tractusx/sldt-semantic-models.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git merge upstream/main --no-edit || true

      - name: Check if there are changes to push
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_ENV
            git push origin main
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Send email on failure or changes
        if: failure() || env.changes == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Action Notification: Sync Fork - ${{ job.status }} - ${{ github.run_started_at }}"
          to: anurag.joshi@dataspacesolutions.com
          from: anurag.joshi@dataspacesolutions.com
          secure: true
          body: |
            GitHub Workflow: ${{ github.workflow }}
            Run Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
