name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/eclipse-tractusx/sldt-semantic-models.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git merge upstream/main --no-edit || true

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git diff HEAD~1 HEAD --name-only) ]]; then
            echo "changes=true" >> $GITHUB_ENV
            echo "Changes detected in repository"
          else
            echo "changes=false" >> $GITHUB_ENV
            echo "No changes detected"
          fi

      - name: Notify on changes or failure
        if: failure() || env.changes == 'true'
        run: |
          echo "::notice::Sync workflow ${{ github.workflow }} ${{ job.status }}"
          echo "::notice::Repository: ${{ github.repository }}"
          echo "::notice::Branch: ${{ github.ref }}"
          echo "::notice::Run URL: ${{ github.serverUrl }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "::notice::Changes detected: ${{ env.changes }}"
